---
title: "StatCafe"
author: "Eli Kravitz"
date: "2/28/2019"
output:
  beamer_presentation:
    includes:
      in_header: preamble.txt
    keep_tex: yes
    slide_level: 3
    theme: metropolis
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Introduction

* I will give an \alert{opinionated} way for you to manage your research workflow in R.
  - I've learned this through trial and error... mostly error.

* Take parts of this you like, ignore parts you don't
  
* Many people are more qualified to talk about this
  - none of them will come here and do it for free. You're stuck with me



### Scenarios (totally not based on personal experience)

* __Scenarios 1__: You work on a project, complete 90% of it, then stop working on it for 2 years. 
  - \alert{Nothing works} on your new computer, you can't locate all the data and files you need. 
  
* __Scenarios 2__: You have a simulation working perfectly. You make a lot of changes. \alert{A few days later} you can't remember why you made these changes, and now \alert{your simulation does not work correctly}.

* __Scenarios 3__: You decide to rewrite most of the paper, show it to your advisor, and they tell you it was better before.
  - You only have the old draft of the paper in PDF. You DO NOT want to retype it.
  
### Rprojects

* I keep all my 